version: '3.8'

services:
  dexer:
    depends_on: 
      - mongo
    build:
      context: .
    container_name: dexer-api
    hostname: dexer
    networks:
      - network-bridge
    ports:
      - 80:${PORT:-8080}
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:?URL de conex達o n達o definida}
    deploy:
      restart_policy:
        condition: unless-stopped

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    hostname: mongo
    networks:
      - network-bridge
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-operator}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:?URL de conex達o n達o definida}
    volumes:
      - mongo:/var/lib/mongodb/data
    deploy:
      restart_policy:
        condition: unless-stopped

volumes:
  mongo:

networks:
  network-bridge:
    driver: bridge
